### ISSUE TITLE
Appwrite Database Schema or screenshot

### ISSUE THREAD

**Issue by ekenechrisjnr** [asutoshranjan/local-ease#1]
Please if its possible to upload a database sample screenshot or exported database file for the project, as the models arent striaght forward enough to create the DB Collections

**Comment by asutoshranjan** [comment]
Hey, I made a tutorial a while back for this project and I there I have created all the collections so you may refer that :)

https://youtu.be/APp9dHVvmPg?si=QIUzehRFVIRsD49F

**Comment by ekenechrisjnr** [comment]
But it seems launch store for sellers does not work?
